#!/bin/sh

PORTS_PACKAGES_XML=http://ports.funtoo.org/packages.xml

fetch() {
  curl -s $PORTS_PACKAGES_XML | xmllint --xpath "string(/packages/category[@name='$1']/package[@name='$2']/@repository)" - 2>/dev/null
}

cat=${1%/*}
pkg=${1#*/}

res=$(fetch $cat $pkg)
[ -n "$res" ] && echo $res || echo "gentoo?"
